# Header
menu:
  Home: /
  Archives: /archives
# rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
  #- links

# Links
links:
  #主题作者: http://arvinxiang.com
  #热前端: http://reqianduan.com
  #远程.work: http://yuancheng.work

favicon:
  small: /images/favicon-16x16-next.png
  medium: /images/favicon-32x32-next.png
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg
  #android_manifest: /images/manifest.json
  #ms_browserconfig: /images/browserconfig.xml

# Duoshuo
duoshuo_shortname: false

# Baidu share
baidushare: false
